name: 'SetUpForE2e'
descriptions: 'Uses the composite action to copy and set up our e2e Selenium and cypress tests'

env:
  PGPASSWORD: submitty_dbuser
  PHP_USER: submitty_php
  PHP_GROUP: submitty_php
  CGI_USER: submitty_cgi
  SUBMITTY_DATA_DIR: /var/local/submitty
  SUBMITTY_INSTALL_DIR: /usr/local/submitty
  SUBMITTY_REPOSITORY: /usr/local/submitty/GIT_CHECKOUT/Submitty
  POSTGRES_HOST: localhost
  PHP_VER: 8.1
  NODE_VERSION: 16
  PYTHON_VERSION: "3.10"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        path: SUBMITTY_CPY/
    - name: Vagrant up
      run: vagrant up
    - name: Run git tests
      run: |
        cd $SUBMITTY_REPOSITORY
        SEMESTER=$(python3 -c 'from datetime import datetime; today = datetime.today(); semester = ("s" if today.month < 7 else "f") + str(today.year)[-2:]; print(semester)')
        sudo python3 /usr/local/submitty/bin/generate_repos.py ${SEMESTER} sample open_homework
        bash tests/git_test.sh
      shell: bash
