name: 'SetUpForE2e'
descriptions: 'Uses the composite action to copy and set up our e2e Selenium and cypress tests'

env:
  PGPASSWORD: submitty_dbuser
  PHP_USER: submitty_php
  PHP_GROUP: submitty_php
  CGI_USER: submitty_cgi
  SUBMITTY_DATA_DIR: /var/local/submitty
  SUBMITTY_INSTALL_DIR: /usr/local/submitty
  SUBMITTY_REPOSITORY: /usr/local/submitty/GIT_CHECKOUT/Submitty
  POSTGRES_HOST: localhost
  PHP_VER: 8.1
  NODE_VERSION: 16
  PYTHON_VERSION: "3.10"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        path: SUBMITTY_CPY/
    - name: Vagrant up
      run: vagrant up
      shell: bash
    - name: Run git tests
      run: vagrant ssh -c 'bash tests/git_test.sh'
      shell: bash
