---
# Submitty Homework Creation (really a build) Ansible script.
# Assumes that course is already set up.


- name: Clone homework repository
  ansible.builtin.git:
    repo: git@gitlab.cs.wallawalla.edu:cptr{{ course_number }}/homework{{ course_number }}.git
    dest: "/var/local/submitty/private_course_repositories/cptr{{ course_number }}/homework{{ course_number }}"
    force: yes
    version: "{{ branch }}"

- name: Generate submitty configs where needed
  ansible.builtin.command:
    cmd: python3 ./main.py /var/local/submitty/private_course_repositories/cptr{{ course_number }}/homework{{ course_number }}/
    chdir: /root/gradeable-generator/
  become: yes
  become_user: root

- name: Run build for specific homework
  ansible.builtin.command:
    cmd: ./BUILD_cptr{{ course_number }}.sh {{ homework }}
    chdir: /var/local/submitty/courses/{{ semester }}/cptr{{ course_number }}/
  become: yes
  become_user: root
