name: Ansible-Install

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Setup SSH 
        shell: bash
        run: |
          ssh-keygen -t rsa -b 4096 -C "github_ci" -N '' -f /home/runner/.ssh/id_rsa
          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 localhost >> /home/runner/.ssh/known_hosts
          cat /home/runner/.ssh/id_rsa.pub >> /home/runner/.ssh/authorized_keys
      - name: Run ansible script
        shell: bash 
        run: |
          ansible-playbook --private-key /home/runner/.ssh/id_rsa -e 'ansible_user=runner, become=yes' -i .setup/ansible/inventory/submitty .setup/ansible/playbooks/submitty_install.yml
