name: Ansible-Install

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: 172.27.0.1
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: submitty_dbuser
          TZ: America/New_York
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps: 
      - uses: actions/checkout@v4
      - name: Setup SSH 
        shell: bash
        run: |
          ssh-keygen -t rsa -b 4096 -C "github_ci" -N '' -f /home/runner/.ssh/id_rsa
          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 localhost >> /home/runner/.ssh/known_hosts
          cat /home/runner/.ssh/id_rsa.pub >> /home/runner/.ssh/authorized_keys
          ssh -T localhost
          sudo systemctl start postgresql
        env:
          # The default PostgreSQL port
          POSTGRES_PASSWORD: submitty_dbuser
          POSTGRES_USER: postgres
      - name: Run ansible script
        shell: bash 
        run: |
          cd .setup/ansible
          ansible-playbook --private-key /home/runner/.ssh/id_rsa -e 'ansible_user=runner' -i inventory/submitty playbooks/submitty_install.yml
        env:
          POSTGRES_PASSWORD: submitty_dbuser
          POSTGRES_USER: postgres
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: install-log
          path: /usr/local/submitty/install.log