name: Notify on Main Failure

on:
  workflow_run:
    workflows: [Submitty CI]
    types: [completed]
    branches:
      - 'main'
jobs:
  Notify-Failure:
    # Runs if on the main Submitty repository, and it's not a pull request (merged PR's act as a commit to main an not a pull request)
    # if: ${{ github.repository == 'Submitty/Submitty' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Zulip on failure
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
            exit 0
      - name: Echo success message
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
            echo ${{ github.event.workflow_run.repository  github.event.workflow_run.head_repository  }}
