name: Notify on Main Failure

on:
  workflow_run:
    workflows: [Submitty CI]
    types: [completed]
    branches:
      - 'main'
jobs:
  Notify-Failure:
    if: ${{ github.event.pull_request.head.repo.full_name == 'Submitty/Submitty' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Zulip on failure
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
            exit 0
      - name: Echo success message
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
            echo "All Tests have passed"
