name: Package Cloud VM

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vagrant-up:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install qemu
        run: brew install qemu
      - name: install vagrant
        run: brew install --cask vagrant
      - name: Setup vagrant for qemu
        run: vagrant plugin install vagrant-qemu
      - name: Vagrant Up
        run: CI=1 vagrant up --provider=qemu
      - name: Validate image
        run: curl --show-error --fail --include http://localhost:1511
      - name: Save image
        run: vagrant package --output submitty.box
      - name: Publish image
        run: |
          vagrant cloud auth login --token ${{ secrets.VAGRANT_CLOUD_TOKEN }}
          vagrant cloud publish reapernsgaming/ubuntu22-dev 100 qemu submitty.box --release --force
          vagrant cloud auth logout