name: Package Cloud VM

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vagrant-up:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install vagrant
        run: |
          brew tap hashicorp/tap
          brew trust --formula hashicorp/tap/vagrant
          brew install hashicorp/tap/hashicorp-vagrant

      - name: install virtual box 7.0.20
        run: |
          curl -LO https://download.virtualbox.org/virtualbox/7.0.20/VirtualBox-7.0.20-163906-OSX.dmg
          hdiutil mount VirtualBox-7.0.20-163906-OSX.dmg
          sudo installer -pkg /Volumes/VirtualBox/VirtualBox.pkg -target /
          hdiutil unmount /Volumes/VirtualBox

      - name: Get latest version
        id: get-version
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "version=${TAG:1}" >> $GITHUB_OUTPUT

      - name: Vagrant Up
        run: CI=1 vagrant up

      - name: Validate image
        run: curl --show-error --fail --include http://localhost:1511

      - name: Save image
        run: vagrant package --output submitty.box

      - name: Publish image
        env:
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET: ${{ secrets.R2_BUCKET }}
          R2_PUBLIC_BASE_URL: ${{ secrets.R2_PUBLIC_BASE_URL }}
        run: |
          bash push-to-r2.sh -f submitty.box -v "${{ steps.get-version.outputs.version }}.$(date +"%y%m%d%H%M")"

      - name: Acquire Job ID
        if: failure()
        id: get-job-id
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          RUN_ATTEMPT: ${{ github.run_attempt }}
          RUNNER_NAME: ${{ runner.name }}
        run: |
          jobs=$(gh api "repos/${REPOSITORY}/actions/runs/${RUN_ID}/attempts/${RUN_ATTEMPT}/jobs")
          job_id=$(echo "$jobs" | jq -r --arg name "$RUNNER_NAME" '.jobs[] | select(.runner_name==$name) | .id')
          echo "job_id=$job_id" >> $GITHUB_OUTPUT

      - name: Send zulip message on failure
        if: failure()
        env:
          ZULIP_AUTHENTICATION: ${{ secrets.ZULIP_AUTHENTICATION }}
          RUN_ID: ${{ github.run_id }}
          JOB_ID: ${{ steps.get-job-id.outputs.job_id }}
        run: |
          curl -X POST https://submitty.zulipchat.com/api/v1/messages -u "$ZULIP_AUTHENTICATION" \
            --data-urlencode 'type=stream' \
            --data-urlencode 'to=Submitty Developer Studio' \
            --data-urlencode 'topic=Vagrant Up Failures' \
            --data-urlencode "content=The Package Vagrant VM Github Action has failed, this means the VM is not saved, and requires attention. View here: https://github.com/Submitty/Submitty/actions/runs/$RUN_ID/job/$JOB_ID"
