name: Vagrant Up

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vagrant-up:
    runs-on: macos-latest

    steps:
      - name: fail to test
        run: |
           exit 1
      - name: Send slack message on failure
        if: failure()
        run: |
           curl -X POST https://submitty.zulipchat.com/api/v1/messages -u ${{ secrets.ZULIP_AUTHENTICATION }} --data-urlencode 'type=stream' --data-urlencode 'to="Submitty Developer Studio"' --data-urlencode 'topic="Vagrant Up Failures"' --data-urlencode 'content="The Vagrant Up Github Action has failed. View here: https://github.com/Submitty/Submitty/actions/runs/${{ github.run_id }}/job/${{ steps.get-job-id.outputs.job_id }}"'
