name: Vagrant Up

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vagrant-up:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      # Installing this is skipped in CI as using it was causing some corruption in
      # attempting to mount the shared folder. The guest and host guest additions
      # versions are close enough that we are fine without it.
      # - run: vagrant plugin install vagrant-vbguest
      # - run: NO_SUBMISSIONS=1 vagrant up ubuntu-22.04
      # - name: Validate image
      #   run: curl --show-error --fail --include http://localhost:1511
      - name: Save to cloud
        id: token
        run: >
            response=$(curl \
            --request POST \
            --header "Content-Type: application/json" \
            --header "Authorization: Bearer ${secrets.VAGRANT_CLOUD_TOKEN}" \
            https://app.vagrantup.com/api/v1/boxes \
            --data "{ "box": { "username": "reapernsgaming", "name": "test123" } }")

            echo $response