name: Vagrant Up

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  vagrant-up:
    runs-on: macos-latest
    steps:
      - name: failed step
        run: |
          exit 1
      - name: Notify if failed job
        if: failed()
        run: "curl -X POST -H 'Content-type: application/json' --data '{"text":"Vagrant Up job has failed"}' ${{ secrets.VAGRANT_UP_WEBHOOK }}"